plugins {
    id 'com.android.application'
}

android {
    compileSdk 34
    ndkVersion '27.0.11902837'

    defaultConfig {
        applicationId = 'com.zltcity.dustandroid'
        minSdkVersion 21
        targetSdkVersion 34
        externalNativeBuild {
            cmake {
                arguments '-DCMAKE_BUILD_TYPE=Debug', '-DANDROID_STL=c++_static'
            }
        }
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'),
                    'proguard-rules.pro'
        }
    }
    externalNativeBuild {
        cmake {
            path 'src/main/cpp/CMakeLists.txt'
        }
    }
    namespace 'com.zltcity.dustandroid'
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
}
